"""
Periodic table data module for ChemMCP element tools.
Contains comprehensive IUPAC data for all 118 elements.
"""

from typing import Optional, Dict, List, Tuple, Any

# Complete periodic table data
# Each entry: symbol, name, atomic_number, atomic_weight, electronegativity (Pauling),
#   electron_config_full, electron_config_noble, category, group, period, block
PERIODIC_TABLE: Dict[str, Dict[str, Any]] = {
    "H":  {"symbol": "H",  "name": "Hydrogen",        "atomic_number": 1,   "atomic_weight": 1.008,    "en_pauling": 2.20, "electron_config": "1s¹",                    "noble_config": "1s¹",                          "category": "nonmetal",       "group": 1,  "period": 1, "block": "s"},
    "He": {"symbol": "He", "name": "Helium",           "atomic_number": 2,   "atomic_weight": 4.0026,   "en_pauling": None,  "electron_config": "1s²",                    "noble_config": "[He]",                           "category": "noble_gas",      "group": 18, "period": 1, "block": "s"},
    "Li": {"symbol": "Li", "name": "Lithium",          "atomic_number": 3,   "atomic_weight": 6.94,     "en_pauling": 0.98, "electron_config": "[He] 2s¹",                "noble_config": "[He] 2s¹",                       "category": "alkali_metal",   "group": 1,  "period": 2, "block": "s"},
    "Be": {"symbol": "Be", "name": "Beryllium",        "atomic_number": 4,   "atomic_weight": 9.0122,   "en_pauling": 1.57, "electron_config": "[He] 2s²",                "noble_config": "[He] 2s²",                       "category": "alkaline_earth",  "group": 2,  "period": 2, "block": "s"},
    "B":  {"symbol": "B",  "name": "Boron",            "atomic_number": 5,   "atomic_weight": 10.81,    "en_pauling": 2.04, "electron_config": "[He] 2s² 2p¹",           "noble_config": "[He] 2s² 2p¹",                  "category": "metalloid",      "group": 13, "period": 2, "block": "p"},
    "C":  {"symbol": "C",  "name": "Carbon",           "atomic_number": 6,   "atomic_weight": 12.011,   "en_pauling": 2.55, "electron_config": "[He] 2s² 2p²",           "noble_config": "[He] 2s² 2p²",                  "category": "nonmetal",       "group": 14, "period": 2, "block": "p"},
    "N":  {"symbol": "N",  "name": "Nitrogen",         "atomic_number": 7,   "atomic_weight": 14.007,   "en_pauling": 3.04, "electron_config": "[He] 2s² 2p³",           "noble_config": "[He] 2s² 2p³",                  "category": "nonmetal",       "group": 15, "period": 2, "block": "p"},
    "O":  {"symbol": "O",  "name": "Oxygen",           "atomic_number": 8,   "atomic_weight": 15.999,   "en_pauling": 3.44, "electron_config": "[He] 2s² 2p⁴",           "noble_config": "[He] 2s² 2p⁴",                  "category": "nonmetal",       "group": 16, "period": 2, "block": "p"},
    "F":  {"symbol": "F",  "name": "Fluorine",         "atomic_number": 9,   "atomic_weight": 18.998,   "en_pauling": 3.98, "electron_config": "[He] 2s² 2p⁵",           "noble_config": "[He] 2s² 2p⁵",                  "category": "halogen",        "group": 17, "period": 2, "block": "p"},
    "Ne": {"symbol": "Ne", "name": "Neon",             "atomic_number": 10,  "atomic_weight": 20.180,   "en_pauling": None,  "electron_config": "[He] 2s² 2p⁶",           "noble_config": "[Ne]",                            "category": "noble_gas",      "group": 18, "period": 2, "block": "p"},
    "Na": {"symbol": "Na", "name": "Sodium",           "atomic_number": 11,  "atomic_weight": 22.990,   "en_pauling": 0.93, "electron_config": "[Ne] 3s¹",                "noble_config": "[Ne] 3s¹",                       "category": "alkali_metal",   "group": 1,  "period": 3, "block": "s"},
    "Mg": {"symbol": "Mg", "name": "Magnesium",        "atomic_number": 12,  "atomic_weight": 24.305,   "en_pauling": 1.31, "electron_config": "[Ne] 3s²",                "noble_config": "[Ne] 3s²",                       "category": "alkaline_earth",  "group": 2,  "period": 3, "block": "s"},
    "Al": {"symbol": "Al", "name": "Aluminum",         "atomic_number": 13,  "atomic_weight": 26.982,   "en_pauling": 1.61, "electron_config": "[Ne] 3s² 3p¹",           "noble_config": "[Ne] 3s² 3p¹",                  "category": "metal",          "group": 13, "period": 3, "block": "p"},
    "Si": {"symbol": "Si", "name": "Silicon",          "atomic_number": 14,  "atomic_weight": 28.085,   "en_pauling": 1.90, "electron_config": "[Ne] 3s² 3p²",           "noble_config": "[Ne] 3s² 3p²",                  "category": "metalloid",      "group": 14, "period": 3, "block": "p"},
    "P":  {"symbol": "P",  "name": "Phosphorus",       "atomic_number": 15,  "atomic_weight": 30.974,   "en_pauling": 2.19, "electron_config": "[Ne] 3s² 3p³",           "noble_config": "[Ne] 3s² 3p³",                  "category": "nonmetal",       "group": 15, "period": 3, "block": "p"},
    "S":  {"symbol": "S",  "name": "Sulfur",           "atomic_number": 16,  "atomic_weight": 32.06,    "en_pauling": 2.58, "electron_config": "[Ne] 3s² 3p⁴",           "noble_config": "[Ne] 3s² 3p⁴",                  "category": "nonmetal",       "group": 16, "period": 3, "block": "p"},
    "Cl": {"symbol": "Cl", "name": "Chlorine",         "atomic_number": 17,  "atomic_weight": 35.45,    "en_pauling": 3.16, "electron_config": "[Ne] 3s² 3p⁵",           "noble_config": "[Ne] 3s² 3p⁵",                  "category": "halogen",        "group": 17, "period": 3, "block": "p"},
    "Ar": {"symbol": "Ar", "name": "Argon",            "atomic_number": 18,  "atomic_weight": 39.948,   "en_pauling": None,  "electron_config": "[Ne] 3s² 3p⁶",           "noble_config": "[Ar]",                            "category": "noble_gas",      "group": 18, "period": 3, "block": "p"},
    "K":  {"symbol": "K",  "name": "Potassium",        "atomic_number": 19,  "atomic_weight": 39.098,   "en_pauling": 0.82, "electron_config": "[Ar] 4s¹",                "noble_config": "[Ar] 4s¹",                       "category": "alkali_metal",   "group": 1,  "period": 4, "block": "s"},
    "Ca": {"symbol": "Ca", "name": "Calcium",          "atomic_number": 20,  "atomic_weight": 40.078,   "en_pauling": 1.00, "electron_config": "[Ar] 4s²",                "noble_config": "[Ar] 4s²",                       "category": "alkaline_earth",  "group": 2,  "period": 4, "block": "s"},
    "Sc": {"symbol": "Sc", "name": "Scandium",         "atomic_number": 21,  "atomic_weight": 44.956,   "en_pauling": 1.36, "electron_config": "[Ar] 3d¹ 4s²",            "noble_config": "[Ar] 3d¹ 4s²",                   "category": "transition_metal","group": 3,  "period": 4, "block": "d"},
    "Ti": {"symbol": "Ti", "name": "Titanium",         "atomic_number": 22,  "atomic_weight": 47.867,   "en_pauling": 1.54, "electron_config": "[Ar] 3d² 4s²",            "noble_config": "[Ar] 3d² 4s²",                   "category": "transition_metal","group": 4,  "period": 4, "block": "d"},
    "V":  {"symbol": "V",  "name": "Vanadium",         "atomic_number": 23,  "atomic_weight": 50.942,   "en_pauling": 1.63, "electron_config": "[Ar] 3d³ 4s²",            "noble_config": "[Ar] 3d³ 4s²",                   "category": "transition_metal","group": 5,  "period": 4, "block": "d"},
    "Cr": {"symbol": "Cr", "name": "Chromium",         "atomic_number": 24,  "atomic_weight": 51.996,   "en_pauling": 1.66, "electron_config": "[Ar] 3d⁵ 4s¹",            "noble_config": "[Ar] 3d⁵ 4s¹",                   "category": "transition_metal","group": 6,  "period": 4, "block": "d"},
    "Mn": {"symbol": "Mn", "name": "Manganese",        "atomic_number": 25,  "atomic_weight": 54.938,   "en_pauling": 1.55, "electron_config": "[Ar] 3d⁵ 4s²",            "noble_config": "[Ar] 3d⁵ 4s²",                   "category": "transition_metal","group": 7,  "period": 4, "block": "d"},
    "Fe": {"symbol": "Fe", "name": "Iron",             "atomic_number": 26,  "atomic_weight": 55.845,   "en_pauling": 1.83, "electron_config": "[Ar] 3d⁶ 4s²",            "noble_config": "[Ar] 3d⁶ 4s²",                   "category": "transition_metal","group": 8,  "period": 4, "block": "d"},
    "Co": {"symbol": "Co", "name": "Cobalt",           "atomic_number": 27,  "atomic_weight": 58.933,   "en_pauling": 1.88, "electron_config": "[Ar] 3d⁷ 4s²",            "noble_config": "[Ar] 3d⁷ 4s²",                   "category": "transition_metal","group": 9,  "period": 4, "block": "d"},
    "Ni": {"symbol": "Ni", "name": "Nickel",           "atomic_number": 28,  "atomic_weight": 58.693,   "en_pauling": 1.91, "electron_config": "[Ar] 3d⁸ 4s²",            "noble_config": "[Ar] 3d⁸ 4s²",                   "category": "transition_metal","group": 10, "period": 4, "block": "d"},
    "Cu": {"symbol": "Cu", "name": "Copper",           "atomic_number": 29,  "atomic_weight": 63.546,   "en_pauling": 1.90, "electron_config": "[Ar] 3d¹⁰ 4s¹",           "noble_config": "[Ar] 3d¹⁰ 4s¹",                  "category": "transition_metal","group": 11, "period": 4, "block": "d"},
    "Zn": {"symbol": "Zn", "name": "Zinc",             "atomic_number": 30,  "atomic_weight": 65.38,    "en_pauling": 1.65, "electron_config": "[Ar] 3d¹⁰ 4s²",           "noble_config": "[Ar] 3d¹⁰ 4s²",                  "category": "transition_metal","group": 12, "period": 4, "block": "d"},
    "Ga": {"symbol": "Ga", "name": "Gallium",          "atomic_number": 31,  "atomic_weight": 69.723,   "en_pauling": 1.81, "electron_config": "[Ar] 3d¹⁰ 4s² 4p¹",       "noble_config": "[Ar] 3d¹⁰ 4s² 4p¹",              "category": "metal",          "group": 13, "period": 4, "block": "p"},
    "Ge": {"symbol": "Ge", "name": "Germanium",        "atomic_number": 32,  "atomic_weight": 72.630,   "en_pauling": 2.01, "electron_config": "[Ar] 3d¹⁰ 4s² 4p²",       "noble_config": "[Ar] 3d¹⁰ 4s² 4p²",              "category": "metalloid",      "group": 14, "period": 4, "block": "p"},
    "As": {"symbol": "As", "name": "Arsenic",          "atomic_number": 33,  "atomic_weight": 74.922,   "en_pauling": 2.18, "electron_config": "[Ar] 3d¹⁰ 4s² 4p³",       "noble_config": "[Ar] 3d¹⁰ 4s² 4p³",              "category": "metalloid",      "group": 15, "period": 4, "block": "p"},
    "Se": {"symbol": "Se", "name": "Selenium",         "atomic_number": 34,  "atomic_weight": 78.971,   "en_pauling": 2.55, "electron_config": "[Ar] 3d¹⁰ 4s² 4p⁴",       "noble_config": "[Ar] 3d¹⁰ 4s² 4p⁴",              "category": "nonmetal",       "group": 16, "period": 4, "block": "p"},
    "Br": {"symbol": "Br", "name": "Bromine",          "atomic_number": 35,  "atomic_weight": 79.904,   "en_pauling": 2.96, "electron_config": "[Ar] 3d¹⁰ 4s² 4p⁵",       "noble_config": "[Ar] 3d¹⁰ 4s² 4p⁵",              "category": "halogen",        "group": 17, "period": 4, "block": "p"},
    "Kr": {"symbol": "Kr", "name": "Krypton",          "atomic_number": 36,  "atomic_weight": 83.798,   "en_pauling": 3.00, "electron_config": "[Ar] 3d¹⁰ 4s² 4p⁶",       "noble_config": "[Kr]",                             "category": "noble_gas",      "group": 18, "period": 4, "block": "p"},
    "Rb": {"symbol": "Rb", "name": "Rubidium",         "atomic_number": 37,  "atomic_weight": 85.468,   "en_pauling": 0.82, "electron_config": "[Kr] 5s¹",                "noble_config": "[Kr] 5s¹",                       "category": "alkali_metal",   "group": 1,  "period": 5, "block": "s"},
    "Sr": {"symbol": "Sr", "name": "Strontium",        "atomic_number": 38,  "atomic_weight": 87.62,    "en_pauling": 0.95, "electron_config": "[Kr] 5s²",                "noble_config": "[Kr] 5s²",                       "category": "alkaline_earth",  "group": 2,  "period": 5, "block": "s"},
    "Y":  {"symbol": "Y",  "name": "Yttrium",          "atomic_number": 39,  "atomic_weight": 88.906,   "en_pauling": 1.22, "electron_config": "[Kr] 4d¹ 5s²",            "noble_config": "[Kr] 4d¹ 5s²",                   "category": "transition_metal","group": 3,  "period": 5, "block": "d"},
    "Zr": {"symbol": "Zr", "name": "Zirconium",        "atomic_number": 40,  "atomic_weight": 91.224,   "en_pauling": 1.33, "electron_config": "[Kr] 4d² 5s²",            "noble_config": "[Kr] 4d² 5s²",                   "category": "transition_metal","group": 4,  "period": 5, "block": "d"},
    "Nb": {"symbol": "Nb", "name": "Niobium",          "atomic_number": 41,  "atomic_weight": 92.906,   "en_pauling": 1.60, "electron_config": "[Kr] 4d⁴ 5s¹",            "noble_config": "[Kr] 4d⁴ 5s¹",                   "category": "transition_metal","group": 5,  "period": 5, "block": "d"},
    "Mo": {"symbol": "Mo", "name": "Molybdenum",       "atomic_number": 42,  "atomic_weight": 95.95,    "en_pauling": 2.16, "electron_config": "[Kr] 4d⁵ 5s¹",            "noble_config": "[Kr] 4d⁵ 5s¹",                   "category": "transition_metal","group": 6,  "period": 5, "block": "d"},
    "Tc": {"symbol": "Tc", "name": "Technetium",       "atomic_number": 43,  "atomic_weight": 98.0,     "en_pauling": 1.90, "electron_config": "[Kr] 4d⁵ 5s²",            "noble_config": "[Kr] 4d⁵ 5s²",                   "category": "transition_metal","group": 7,  "period": 5, "block": "d"},
    "Ru": {"symbol": "Ru", "name": "Ruthenium",        "atomic_number": 44,  "atomic_weight": 101.07,   "en_pauling": 2.20, "electron_config": "[Kr] 4d⁷ 5s¹",            "noble_config": "[Kr] 4d⁷ 5s¹",                   "category": "transition_metal","group": 8,  "period": 5, "block": "d"},
    "Rh": {"symbol": "Rh", "name": "Rhodium",          "atomic_number": 45,  "atomic_weight": 102.91,   "en_pauling": 2.28, "electron_config": "[Kr] 4d⁸ 5s¹",            "noble_config": "[Kr] 4d⁸ 5s¹",                   "category": "transition_metal","group": 9,  "period": 5, "block": "d"},
    "Pd": {"symbol": "Pd", "name": "Palladium",        "atomic_number": 46,  "atomic_weight": 106.42,   "en_pauling": 2.20, "electron_config": "[Kr] 4d¹⁰",               "noble_config": "[Kr] 4d¹⁰",                        "category": "transition_metal","group": 10, "period": 5, "block": "d"},
    "Ag": {"symbol": "Ag", "name": "Silver",           "atomic_number": 47,  "atomic_weight": 107.87,   "en_pauling": 1.93, "electron_config": "[Kr] 4d¹⁰ 5s¹",           "noble_config": "[Kr] 4d¹⁰ 5s¹",                  "category": "transition_metal","group": 11, "period": 5, "block": "d"},
    "Cd": {"symbol": "Cd", "name": "Cadmium",          "atomic_number": 48,  "atomic_weight": 112.41,   "en_pauling": 1.69, "electron_config": "[Kr] 4d¹⁰ 5s²",           "noble_config": "[Kr] 4d¹⁰ 5s²",                  "category": "transition_metal","group": 12, "period": 5, "block": "d"},
    "In": {"symbol": "In", "name": "Indium",           "atomic_number": 49,  "atomic_weight": 114.82,   "en_pauling": 1.78, "electron_config": "[Kr] 4d¹⁰ 5s² 5p¹",       "noble_config": "[Kr] 4d¹⁰ 5s² 5p¹",              "category": "metal",          "group": 13, "period": 5, "block": "p"},
    "Sn": {"symbol": "Sn", "name": "Tin",              "atomic_number": 50,  "atomic_weight": 118.71,   "en_pauling": 1.96, "electron_config": "[Kr] 4d¹⁰ 5s² 5p²",       "noble_config": "[Kr] 4d¹⁰ 5s² 5p²",              "category": "metal",          "group": 14, "period": 5, "block": "p"},
    "Sb": {"symbol": "Sb", "name": "Antimony",         "atomic_number": 51,  "atomic_weight": 121.76,   "en_pauling": 2.05, "electron_config": "[Kr] 4d¹⁰ 5s² 5p³",       "noble_config": "[Kr] 4d¹⁰ 5s² 5p³",              "category": "metalloid",      "group": 15, "period": 5, "block": "p"},
    "Te": {"symbol": "Te", "name": "Tellurium",        "atomic_number": 52,  "atomic_weight": 127.60,   "en_pauling": 2.10, "electron_config": "[Kr] 4d¹⁰ 5s² 5p⁴",       "noble_config": "[Kr] 4d¹⁰ 5s² 5p⁴",              "category": "metalloid",      "group": 16, "period": 5, "block": "p"},
    "I":  {"symbol": "I",  "name": "Iodine",           "atomic_number": 53,  "atomic_weight": 126.90,   "en_pauling": 2.66, "electron_config": "[Kr] 4d¹⁰ 5s² 5p⁵",       "noble_config": "[Kr] 4d¹⁰ 5s² 5p⁵",              "category": "halogen",        "group": 17, "period": 5, "block": "p"},
    "Xe": {"symbol": "Xe", "name": "Xenon",            "atomic_number": 54,  "atomic_weight": 129.29,   "en_pauling": 2.60, "electron_config": "[Kr] 4d¹⁰ 5s² 5p⁶",       "noble_config": "[Xe]",                             "category": "noble_gas",      "group": 18, "period": 5, "block": "p"},
    "Cs": {"symbol": "Cs", "name": "Cesium",           "atomic_number": 55,  "atomic_weight": 132.91,   "en_pauling": 0.79, "electron_config": "[Xe] 6s¹",                "noble_config": "[Xe] 6s¹",                       "category": "alkali_metal",   "group": 1,  "period": 6, "block": "s"},
    "Ba": {"symbol": "Ba", "name": "Barium",           "atomic_number": 56,  "atomic_weight": 137.33,   "en_pauling": 0.89, "electron_config": "[Xe] 6s²",                "noble_config": "[Xe] 6s²",                       "category": "alkaline_earth",  "group": 2,  "period": 6, "block": "s"},
    "La": {"symbol": "La", "name": "Lanthanum",        "atomic_number": 57,  "atomic_weight": 138.91,   "en_pauling": 1.10, "electron_config": "[Xe] 5d¹ 6s²",            "noble_config": "[Xe] 5d¹ 6s²",                   "category": "lanthanide",     "group": 3,  "period": 6, "block": "f"},
    "Ce": {"symbol": "Ce", "name": "Cerium",           "atomic_number": 58,  "atomic_weight": 140.12,   "en_pauling": 1.12, "electron_config": "[Xe] 4f¹ 5d¹ 6s²",        "noble_config": "[Xe] 4f¹ 5d¹ 6s²",                 "category": "lanthanide",     "group": None,"period": 6, "block": "f"},
    "Pr": {"symbol": "Pr", "name": "Praseodymium",     "atomic_number": 59,  "atomic_weight": 140.91,   "en_pauling": 1.13, "electron_config": "[Xe] 4f³ 6s²",             "noble_config": "[Xe] 4f³ 6s²",                    "category": "lanthanide",     "group": None,"period": 6, "block": "f"},
    "Nd": {"symbol": "Nd", "name": "Neodymium",       "atomic_number": 60,  "atomic_weight": 144.24,   "en_pauling": 1.14, "electron_config": "[Xe] 4f⁴ 6s²",             "noble_config": "[Xe] 4f⁴ 6s²",                    "category": "lanthanide",     "group": None,"period": 6, "block": "f"},
    "Pm": {"symbol": "Pm", "name": "Promethium",       "atomic_number": 61,  "atomic_weight": 145.0,    "en_pauling": 1.13, "electron_config": "[Xe] 4f⁵ 6s²",             "noble_config": "[Xe] 4f⁵ 6s²",                    "category": "lanthanide",     "group": None,"period": 6, "block": "f"},
    "Sm": {"symbol": "Sm", "name": "Samarium",         "atomic_number": 62,  "atomic_weight": 150.36,   "en_pauling": 1.17, "electron_config": "[Xe] 4f⁶ 6s²",             "noble_config": "[Xe] 4f⁶ 6s²",                    "category": "lanthanide",     "group": None,"period": 6, "block": "f"},
    "Eu": {"symbol": "Eu", "name": "Europium",         "atomic_number": 63,  "atomic_weight": 151.96,   "en_pauling": 1.20, "electron_config": "[Xe] 4f⁷ 6s²",             "noble_config": "[Xe] 4f⁷ 6s²",                    "category": "lanthanide",     "group": None,"period": 6, "block": "f"},
    "Gd": {"symbol": "Gd", "name": "Gadolinium",       "atomic_number": 64,  "atomic_weight": 157.25,   "en_pauling": 1.20, "electron_config": "[Xe] 4f⁷ 5d¹ 6s²",        "noble_config": "[Xe] 4f⁷ 5d¹ 6s²",                 "category": "lanthanide",     "group": None,"period": 6, "block": "f"},
    "Tb": {"symbol": "Tb", "name": "Terbium",          "atomic_number": 65,  "atomic_weight": 158.93,   "en_pauling": 1.20, "electron_config": "[Xe] 4f⁹ 6s²",             "noble_config": "[Xe] 4f⁹ 6s²",                    "category": "lanthanide",     "group": None,"period": 6, "block": "f"},
    "Dy": {"symbol": "Dy", "name": "Dysprosium",       "atomic_number": 66,  "atomic_weight": 162.50,   "en_pauling": 1.22, "electron_config": "[Xe] 4f¹⁰ 6s²",            "noble_config": "[Xe] 4f¹⁰ 6s²",                   "category": "lanthanide",     "group": None,"period": 6, "block": "f"},
    "Ho": {"symbol": "Ho", "name": "Holmium",          "atomic_number": 67,  "atomic_weight": 164.93,   "en_pauling": 1.23, "electron_config": "[Xe] 4f¹¹ 6s²",            "noble_config": "[Xe] 4f¹¹ 6s²",                   "category": "lanthanide",     "group": None,"period": 6, "block": "f"},
    "Er": {"symbol": "Er", "name": "Erbium",           "atomic_number": 68,  "atomic_weight": 167.26,   "en_pauling": 1.24, "electron_config": "[Xe] 4f¹² 6s²",            "noble_config": "[Xe] 4f¹² 6s²",                   "category": "lanthanide",     "group": None,"period": 6, "block": "f"},
    "Tm": {"symbol": "Tm", "name": "Thulium",          "atomic_number": 69,  "atomic_weight": 168.93,   "en_pauling": 1.25, "electron_config": "[Xe] 4f¹³ 6s²",            "noble_config": "[Xe] 4f¹³ 6s²",                   "category": "lanthanide",     "group": None,"period": 6, "block": "f"},
    "Yb": {"symbol": "Yb", "name": "Ytterbium",        "atomic_number": 70,  "atomic_weight": 173.05,   "en_pauling": 1.10, "electron_config": "[Xe] 4f¹⁴ 6s²",            "noble_config": "[Xe] 4f¹⁴ 6s²",                   "category": "lanthanide",     "group": None,"period": 6, "block": "f"},
    "Lu": {"symbol": "Lu", "name": "Lutetium",         "atomic_number": 71,  "atomic_weight": 174.97,   "en_pauling": 1.27, "electron_config": "[Xe] 4f¹⁴ 5d¹ 6s²",        "noble_config": "[Xe] 4f¹⁴ 5d¹ 6s²",                 "category": "lanthanide",     "group": 3,  "period": 6, "block": "d"},
    "Hf": {"symbol": "Hf", "name": "Hafnium",          "atomic_number": 72,  "atomic_weight": 178.49,   "en_pauling": 1.30, "electron_config": "[Xe] 4f¹⁴ 5d² 6s²",        "noble_config": "[Xe] 4f¹⁴ 5d² 6s²",                 "category": "transition_metal","group": 4,  "period": 6, "block": "d"},
    "Ta": {"symbol": "Ta", "name": "Tantalum",         "atomic_number": 73,  "atomic_weight": 180.95,   "en_pauling": 1.50, "electron_config": "[Xe] 4f¹⁴ 5d³ 6s²",        "noble_config": "[Xe] 4f¹⁴ 5d³ 6s²",                 "category": "transition_metal","group": 5,  "period": 6, "block": "d"},
    "W":  {"symbol": "W",  "name": "Tungsten",          "atomic_number": 74,  "atomic_weight": 183.84,   "en_pauling": 2.36, "electron_config": "[Xe] 4f¹⁴ 5d⁴ 6s²",        "noble_config": "[Xe] 4f¹⁴ 5d⁴ 6s²",                 "category": "transition_metal","group": 6,  "period": 6, "block": "d"},
    "Re": {"symbol": "Re", "name": "Rhenium",          "atomic_number": 75,  "atomic_weight": 186.21,   "en_pauling": 1.90, "electron_config": "[Xe] 4f¹⁴ 5d⁵ 6s²",        "noble_config": "[Xe] 4f¹⁴ 5d⁵ 6s²",                 "category": "transition_metal","group": 7,  "period": 6, "block": "d"},
    "Os": {"symbol": "Os", "name": "Osmium",           "atomic_number": 76,  "atomic_weight": 190.23,   "en_pauling": 2.20, "electron_config": "[Xe] 4f¹⁴ 5d⁶ 6s²",        "noble_config": "[Xe] 4f¹⁴ 5d⁶ 6s²",                 "category": "transition_metal","group": 8,  "period": 6, "block": "d"},
    "Ir": {"symbol": "Ir", "name": "Iridium",          "atomic_number": 77,  "atomic_weight": 192.22,   "en_pauling": 2.20, "electron_config": "[Xe] 4f¹⁴ 5d⁷ 6s²",        "noble_config": "[Xe] 4f¹⁴ 5d⁷ 6s²",                 "category": "transition_metal","group": 9,  "period": 6, "block": "d"},
    "Pt": {"symbol": "Pt", "name": "Platinum",         "atomic_number": 78,  "atomic_weight": 195.08,   "en_pauling": 2.28, "electron_config": "[Xe] 4f¹⁴ 5d⁹ 6s¹",        "noble_config": "[Xe] 4f¹⁴ 5d⁹ 6s¹",                  "category": "transition_metal","group": 10, "period": 6, "block": "d"},
    "Au": {"symbol": "Au", "name": "Gold",             "atomic_number": 79,  "atomic_weight": 196.97,   "en_pauling": 2.54, "electron_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",        "noble_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s¹",                 "category": "transition_metal","group": 11, "period": 6, "block": "d"},
    "Hg": {"symbol": "Hg", "name": "Mercury",          "atomic_number": 80,  "atomic_weight": 200.59,   "en_pauling": 2.00, "electron_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s²",        "noble_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s²",                 "category": "transition_metal","group": 12, "period": 6, "block": "d"},
    "Tl": {"symbol": "Tl", "name": "Thallium",         "atomic_number": 81,  "atomic_weight": 204.38,   "en_pauling": 1.62, "electron_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",     "noble_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p¹",            "category": "metal",          "group": 13, "period": 6, "block": "p"},
    "Pb": {"symbol": "Pb", "name": "Lead",             "atomic_number": 82,  "atomic_weight": 207.2,    "en_pauling": 2.33, "electron_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",     "noble_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p²",            "category": "metal",          "group": 14, "period": 6, "block": "p"},
    "Bi": {"symbol": "Bi", "name": "Bismuth",          "atomic_number": 83,  "atomic_weight": 208.98,   "en_paul": 2.02, "electron_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",     "noble_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p³",            "category": "metal",          "group": 15, "period": 6, "block": "p"},
    "Po": {"symbol": "Po", "name": "Polonium",         "atomic_number": 84,  "atomic_weight": 209.0,    "en_pauling": 2.00, "electron_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",     "noble_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁴",            "category": "metalloid",      "group": 16, "period": 6, "block": "p"},
    "At": {"symbol": "At", "name": "Astatine",         "atomic_number": 85,  "atomic_weight": 210.0,    "en_pauling": 2.20, "electron_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",     "noble_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁵",            "category": "halogen",        "group": 17, "period": 6, "block": "p"},
    "Rn": {"symbol": "Rn", "name": "Radon",            "atomic_number": 86,  "atomic_weight": 222.0,    "en_pauling": None,  "electron_config": "[Xe] 4f¹⁴ 5d¹⁰ 6s² 6p⁶",     "noble_config": "[Rn]",                             "category": "noble_gas",      "group": 18, "period": 6, "block": "p"},
    "Fr": {"symbol": "Fr", "name": "Francium",         "atomic_number": 87,  "atomic_weight": 223.0,    "en_pauling": 0.70, "electron_config": "[Rn] 7s¹",                "noble_config": "[Rn] 7s¹",                       "category": "alkali_metal",   "group": 1,  "period": 7, "block": "s"},
    "Ra": {"symbol": "Ra", "name": "Radium",           "atomic_number": 88,  "atomic_weight": 226.0,    "en_pauling": 0.90, "electron_config": "[Rn] 7s²",                "noble_config": "[Rn] 7s²",                       "category": "alkaline_earth",  "group": 2,  "period": 7, "block": "s"},
    "Ac": {"symbol": "Ac", "name": "Actinium",         "atomic_number": 89,  "atomic_weight": 227.0,    "en_pauling": 1.10, "electron_config": "[Rn] 6d¹ 7s²",            "noble_config": "[Rn] 6d¹ 7s²",                     "category": "actinide",       "group": 3,  "period": 7, "block": "f"},
    "Th": {"symbol": "Th", "name": "Thorium",          "atomic_number": 90,  "atomic_weight": 232.04,   "en_pauling": 1.30, "electron_config": "[Rn] 6d² 7s²",            "noble_config": "[Rn] 6d² 7s²",                     "category": "actinide",       "group": None,"period": 7, "block": "f"},
    "Pa": {"symbol": "Pa", "name": "Protactinium",     "atomic_number": 91,  "atomic_weight": 231.04,   "en_pauling": 1.50, "electron_config": "[Rn] 5f² 6d¹ 7s²",        "noble_config": "[Rn] 5f² 6d¹ 7s²",                   "category": "actinide",       "group": None,"period": 7, "block": "f"},
    "U":  {"symbol": "U",  "name": "Uranium",          "atomic_number": 92,  "atomic_weight": 238.03,   "en_pauling": 1.38, "electron_config": "[Rn] 5f³ 6d¹ 7s²",        "noble_config": "[Rn] 5f³ 6d¹ 7s²",                   "category": "actinide",       "group": None,"period": 7, "block": "f"},
    "Np": {"symbol": "Np", "name": "Neptunium",       "atomic_number": 93,  "atomic_weight": 237.0,    "en_pauling": 1.36, "electron_config": "[Rn] 5f⁴ 6d¹ 7s²",        "noble_config": "[Rn] 5f⁴ 6d¹ 7s²",                   "category": "actinide",       "group": None,"period": 7, "block": "f"},
    "Pu": {"symbol": "Pu", "name": "Plutonium",        "atomic_number": 94,  "atomic_weight": 244.0,    "en_pauling": 1.28, "electron_config": "[Rn] 5f⁶ 7s²",             "noble_config": "[Rn] 5f⁶ 7s²",                      "category": "actinide",       "group": None,"period": 7, "block": "f"},
    "Am": {"symbol": "Am", "name": "Americium",        "atomic_number": 95,  "atomic_weight": 243.0,    "en_pauling": 1.30, "electron_config": "[Rn] 5f⁷ 7s²",             "noble_config": "[Rn] 5f⁷ 7s²",                      "category": "actinide",       "group": None,"period": 7, "block": "f"},
    "Cm": {"symbol": "Cm", "name": "Curium",           "atomic_number": 96,  "atomic_weight": 247.0,    "en_pauling": 1.30, "electron_config": "[Rn] 5f⁷ 6d¹ 7s²",        "noble_config": "[Rn] 5f⁷ 6d¹ 7s²",                   "category": "actinide",       "group": None,"period": 7, "block": "f"},
    "Bk": {"symbol": "Bk", "name": "Berkelium",        "atomic_number": 97,  "atomic_weight": 247.0,    "en_pauling": 1.30, "electron_config": "[Rn] 5f⁹ 7s²",             "noble_config": "[Rn] 5f⁹ 7s²",                      "category": "actinide",       "group": None,"period": 7, "block": "f"},
    "Cf": {"symbol": "Cf", "name": "Californium",      "atomic_number": 98,  "atomic_weight": 251.0,    "en_pauling": 1.30, "electron_config": "[Rn] 5f¹⁰ 7s²",            "noble_config": "[Rn] 5f¹⁰ 7s²",                     "category": "actinide",       "group": None,"period": 7, "block": "f"},
    "Es": {"symbol": "Es", "name": "Einsteinium",      "atomic_number": 99,  "atomic_weight": 252.0,    "en_pauling": 1.30, "electron_config": "[Rn] 5f¹¹ 7s²",            "noble_config": "[Rn] 5f¹¹ 7s²",                     "category": "actinide",       "group": None,"period": 7, "block": "f"},
    "Fm": {"symbol": "Fm", "name": "Fermium",          "atomic_number": 100, "atomic_weight": 257.0,    "en_pauling": 1.30, "electron_config": "[Rn] 5f¹² 7s²",            "noble_config": "[Rn] 5f¹² 7s²",                     "category": "actinide",       "group": None,"period": 7, "block": "f"},
    "Md": {"symbol": "Md", "name": "Mendelevium",      "atomic_number": 101, "atomic_weight": 258.0,    "en_pauling": 1.30, "electron_config": "[Rn] 5f¹³ 7s²",            "noble_config": "[Rn] 5f¹³ 7s²",                     "category": "actinide",       "group": None,"period": 7, "block": "f"},
    "No": {"symbol": "No", "name": "Nobelium",         "atomic_number": 102, "atomic_weight": 259.0,    "en_pauling": 1.30, "electron_config": "[Rn] 5f¹⁴ 7s²",            "noble_config": "[Rn] 5f¹⁴ 7s²",                     "category": "actinide",       "group": None,"period": 7, "block": "f"},
    "Lr": {"symbol": "Lr", "name": "Lawrencium",       "atomic_number": 103, "atomic_weight": 262.0,    "en_pauling": None,  "electron_config": "[Rn] 5f¹⁴ 6d¹ 7s²",        "noble_config": "[Rn] 5f¹⁴ 6d¹ 7s²",                   "category": "actinide",       "group": 3,  "period": 7, "block": "d"},
    "Rf": {"symbol": "Rf", "name": "Rutherfordium",    "atomic_number": 104, "atomic_weight": 267.0,    "en_pauling": None,  "electron_config": "[Rn] 5f¹⁴ 6d² 7s²",        "noble_config": "[Rn] 5f¹⁴ 6d² 7s²",                   "category": "transition_metal","group": 4,  "period": 7, "block": "d"},
    "Db": {"symbol": "Db", "name": "Dubnium",          "atomic_number": 105, "atomic_weight": 268.0,    "en_pauling": None,  "electron_config": "[Rn] 5f¹⁴ 6d³ 7s²",        "noble_config": "[Rn] 5f¹⁴ 6d³ 7s²",                   "category": "transition_metal","group": 5,  "period": 7, "block": "d"},
    "Sg": {"symbol": "Sg", "name": "Seaborgium",       "atomic_number": 106, "atomic_weight": 269.0,    "en_pauling": None,  "electron_config": "[Rn] 5f¹⁴ 6d⁴ 7s²",        "noble_config": "[Rn] 5f¹⁴ 6d⁴ 7s²",                   "category": "transition_metal","group": 6,  "period": 7, "block": "d"},
    "Bh": {"symbol": "Bh", "name": "Bohrium",          "atomic_number": 107, "atomic_weight": 270.0,    "en_pauling": None,  "electron_config": "[Rn] 5f¹⁴ 6d⁵ 7s²",        "noble_config": "[Rn] 5f¹⁴ 6d⁵ 7s²",                   "category": "transition_metal","group": 7,  "period": 7, "block": "d"},
    "Hs": {"symbol": "Hs", "name": "Hassium",          "atomic_number": 108, "atomic_weight": 270.0,    "en_pauling": None,  "electron_config": "[Rn] 5f¹⁴ 6d⁶ 7s²",        "noble_config": "[Rn] 5f¹⁴ 6d⁶ 7s²",                   "category": "transition_metal","group": 8,  "period": 7, "block": "d"},
    "Mt": {"symbol": "Mt", "name": "Meitnerium",      "atomic_number": 109, "atomic_weight": 278.0,    "en_pauling": None,  "electron_config": "[Rn] 5f¹⁴ 6d⁷ 7s²",        "noble_config": "[Rn] 5f¹⁴ 6d⁷ 7s²",                   "category": "transition_metal","group": 9,  "period": 7, "block": "d"},
    "Ds": {"symbol": "Ds", "name": "Darmstadtium",     "atomic_number": 110, "atomic_weight": 281.0,    "en_pauling": None,  "electron_config": "[Rn] 5f¹⁴ 6d⁸ 7s²",        "noble_config": "[Rn] 5f¹⁴ 6d⁸ 7s²",                   "category": "transition_metal","group": 10, "period": 7, "block": "d"},
    "Rg": {"symbol": "Rg", "name": "Roentgenium",      "atomic_number": 111, "atomic_weight": 282.0,    "en_pauling": None,  "electron_config": "[Rn] 5f¹⁴ 6d⁹ 7s²",        "noble_config": "[Rn] 5f¹⁴ 6d⁹ 7s²",                   "category": "transition_metal","group": 11, "period": 7, "block": "d"},
    "Cn": {"symbol": "Cn", "name": "Copernicium",      "atomic_number": 112, "atomic_weight": 285.0,    "en_pauling": None,  "electron_config": "[Rn] 5f¹⁰ 6d⁹ 7s²",        "noble_config": "[Rn] 5f¹⁰ 6d⁹ 7s²",                   "category": "transition_metal","group": 12, "period": 7, "block": "d"},
    "Nh": {"symbol": "Nh", "name": "Nihonium",         "atomic_number": 113, "atomic_weight": 286.0,    "en_pauling": None,  "electron_config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",     "noble_config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p¹",            "category": "metal",          "group": 13, "period": 7, "block": "p"},
    "Fl": {"symbol": "Fl", "name": "Flerovium",        "atomic_number": 114, "atomic_weight": 289.0,    "en_pauling": None,  "electron_config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",     "noble_config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p²",            "category": "metal",          "group": 14, "period": 7, "block": "p"},
    "Mc": {"symbol": "Mc", "name": "Moscovium",       "atomic_number": 115, "atomic_weight": 290.0,    "en_pauling": None,  "electron_config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",     "noble_config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p³",            "category": "metal",          "group": 15, "period": 7, "block": "p"},
    "Lv": {"symbol": "Lv", "name": "Livermorium",      "atomic_number": 116, "atomic_weight": 293.0,    "en_pauling": None,  "electron_config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",     "noble_config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁴",            "category": "metal",          "group": 16, "period": 7, "block": "p"},
    "Ts": {"symbol": "Ts", "name": "Tennessine",       "atomic_number": 117, "atomic_weight": 294.0,    "en_pauling": None,  "electron_config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",     "noble_config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁵",            "category": "halogen",        "group": 17, "period": 7, "block": "p"},
    "Og": {"symbol": "Og", "name": "Oganesson",        "atomic_number": 118, "atomic_weight": 294.0,    "en_pauling": None,  "electron_config": "[Rn] 5f¹⁴ 6d¹⁰ 7s² 7p⁶",     "noble_config": "[Og]",                             "category": "noble_gas",      "group": 18, "period": 7, "block": "p"},
}

# Atomic number to symbol mapping
ATOMIC_NUMBER_TO_SYMBOL: Dict[int, str] = {
    data["atomic_number"]: sym for sym, data in PERIODIC_TABLE.items()
}


def get_element(symbol_or_number) -> dict:
    """Get element data by symbol or atomic number."""
    if isinstance(symbol_or_number, int):
        symbol = ATOMIC_NUMBER_TO_SYMBOL.get(symbol_or_number)
        if symbol is None:
            return None
        return PERIODIC_TABLE[symbol].copy()
    else:
        symbol = symbol_or_number.strip().capitalize()
        # Handle special cases
        symbol_map = {
            "fe": "Fe", "co": "Co", "ni": "Ni", "cu": "Cu", "zn": "Zn",
            "se": "Se", "no": "No", "as": "As", "be": "Be", "nb": "Nb",
            "mo": "Mo", "tc": "Tc", "ru": "Ru", "rh": "Rh", "pd": "Pd",
            "ag": "Ag", "cd": "Cd", "in": "In", "sn": "Sn", "sb": "Sb",
            "te": "Te", "xe": "Xe", "cs": "Cs", "ba": "Ba", "lu": "Lu",
            "hf": "Hf", "ta": "Ta", "re": "Re", "os": "Os", "ir": "Ir",
            "pt": "Pt", "au": "Au", "hg": "Hg", "tl": "Tl", "pb": "Pb",
            "bi": "Bi", "po": "Po", "at": "At", "rn": "Rn", "fr": "Fr",
            "ra": "Ra", "ac": "Ac", "th": "Th", "pa": "Pa", "u": "U",
            "np": "Np", "pu": "Pu", "am": "Am", "cm": "Cm", "bk": "Bk",
            "cf": "Cf", "es": "Es", "fm": "Fm", "md": "Md", "no": "No",
            "lr": "Lr", "rf": "Rf", "db": "Db", "sg": "Sg", "bh": "Bh",
            "hs": "Hs", "mt": "Mt", "ds": "Ds", "rg": "Rg", "cn": "Cn",
            "nh": "Nh", "fl": "Fl", "mc": "Mc", "lv": "Lv", "ts": "Ts",
            "og": "Og",
        }
        resolved = symbol_map.get(symbol, symbol.title() if len(symbol) > 1 else symbol.upper())
        return PERIODIC_TABLE.get(resolved)


def validate_element(symbol_or_number) -> str:
    """Validate and return canonical element symbol."""
    data = get_element(symbol_or_number)
    if data is None:
        raise ValueError(f"Unknown element: {symbol_or_number}")
    return data["symbol"]
